name: Serverless Deploy

on:
  push:
    branches:
      - main

jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.commit_message_check.outputs.should_deploy }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get last commit message
        id: get_commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Determine if deploy should run
        id: commit_message_check
        run: echo "::set-output name=should_deploy::$(if echo '${{ steps.get_commit_message.outputs.message }}' | grep -q 'deploy-dev'; then echo 'true'; else echo 'false'; fi)"

  deploy:
    runs-on: ubuntu-latest
    needs: check_commit
    if: needs.check_commit.outputs.should_deploy == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS Lambda
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
